### ISSUE TITLE
Clean Up Code

### ISSUE THREAD

**Issue by joscha-st** [joscha-st/bad_walden_stadtwerke#59]
Especially, take a look on outdated imports and code style that does not work with our conventions

**Comment by ArchibaldTheFirst** [comment]
-Cleancode practices.
-Remove unused imports -> Unused Code in General
-Generate Java Docs.

**Comment by joscha-st** [comment]
- ensure consistant

**Comment by sternlis** [comment]
- fix Rechtschreibung: z.B. Neukundenaufnahme, Heiztarif, ... (mit UI abgleichen)
