### ISSUE TITLE
Fix Language File add translation for Welcome Label 2 

### ISSUE THREAD

**Issue by ArchibaldTheFirst** [joscha-st/bad_walden_stadtwerke#62]

**Comment by LukasStrickler** [comment]
pls clarify @ArchibaldTheFirst

**Comment by ArchibaldTheFirst** [comment]
I spotted 2 mistakes in the language file and one missing tranlation. Have not opened up a branch for it but i will after my next merge goes through

**Comment by ArchibaldTheFirst** [comment]
Done
