### ISSUE TITLE
Unintuitiveness in AI -> after Electricity tarif --> others --> Gas and heat pump are hidden in other tabs.

### ISSUE THREAD

**Issue by ArchibaldTheFirst** [joscha-st/bad_walden_stadtwerke#65]
You choose an electricity tarif and then you come to the "others" section. You need to read a tiny text and have the option to click on a prominent big next. Gas and Heatpump are hidden behind tabs. Seems a little unintuitve that you have to click on them to find out more. Maybe solve this with a checkbox popup? "Do you heat with gas, heatpump, others? and then display the relevant page?

**Comment by LukasStrickler** [comment]
won't implement, design we have was accepted by product team

Will implement better font styling for clarity

**Comment by ArchibaldTheFirst** [comment]
Thats fine for shure!
