### ISSUE TITLE
Update db modelling (datagrip)

### ISSUE THREAD

**Issue by LukasStrickler** [joscha-st/bad_walden_stadtwerke#85]
- add multi language support
- ensure there is a table of tariffs and one for contracts
- remove shared tables and mention api connection to "Rathaus" 
   - fetch household of a userid
   - send user / pw to endpoint to get back token / user class

- [ ] export sql code and update readme

**Comment by joscha-st** [comment]
also dont forget to model new "has completed signup" attribute or similar per household
